---
apiVersion: getambassador.io/v2
kind: Mapping
metadata:
  name: emojivoto
  namespace: emojivoto
spec:
  prefix: /
  service: web-svc.emojivoto:80
  rewrite: ""
  host: emojivoto.kcna21.linkerd.io